### PR TITLE
Add option to mark unread

### PR DESCRIPTION
**Pull request by michaeleldar**
Not tested, but it should work

### CODE REVIEW

**Comment by mybearworld** [comment]
That button would just act as the "Reset read date" button like this, though.

**Comment by michaeleldar** [comment]
Yeah I just realised that.

How would I change that?

**Comment by mybearworld** [comment]
> Yeah I just realised that.
> 
> How would I change that?

It would probably require changing the way marking as read currently works

**Comment by mybearworld** [comment]
In general, you could probably just pin posts you want to leave unread.

**Pull request closed without merging**
